services:
  sanbi:
    image: sanbi-ecosystem:${TAG}
    container_name: sanbi-ecosystem
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - /opt/apps/sarva/web/sanbi-ecosystem-risk-atlas/.env
    ports:
      - "8503:8501"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped